Models/ErrorViewModel.cs
namespace pruevas_de_a_5.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Producto.cs
using System.ComponentModel.DataAnnotations;

namespace pruevas_de_a_5.Models
{
    public class Producto
    {
        [Key]
        public int Cod_producto { get; set; }
        public string Nom_producto { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
        public string Fecha_Elaboracio { get; set; }
        public string Fecha_Caducidad { get; set; }
        public int CodCategoria { get; set; }
        public string CodProveedor { get; set; }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using pruevas_de_a_5.Models;
using System.Diagnostics;

namespace pruevas_de_a_5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using pruevas_de_a_5.Data;
using pruevas_de_a_5.Models;

namespace pruevas_de_a_5.Controllers
{
    public class ProductoesController : Controller
    {
        private readonly pruevas_de_a_5Context _context;

        public ProductoesController(pruevas_de_a_5Context context)
        {
            _context = context;
        }

        // GET: Productoes
        public async Task<IActionResult> Index()
        {
              return _context.Producto != null ? 
                          View(await _context.Producto.ToListAsync()) :
                          Problem("Entity set 'pruevas_de_a_5Context.Producto'  is null.");
        }

        // GET: Productoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Producto == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .FirstOrDefaultAsync(m => m.Cod_producto == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Productoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Cod_producto,Nom_producto,Precio,Cantidad,Fecha_Elaboracio,Fecha_Caducidad,CodCategoria,CodProveedor")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Productoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Producto == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: Productoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Cod_producto,Nom_producto,Precio,Cantidad,Fecha_Elaboracio,Fecha_Caducidad,CodCategoria,CodProveedor")] Producto producto)
        {
            if (id != producto.Cod_producto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.Cod_producto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Productoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Producto == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .FirstOrDefaultAsync(m => m.Cod_producto == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Productoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Producto == null)
            {
                return Problem("Entity set 'pruevas_de_a_5Context.Producto'  is null.");
            }
            var producto = await _context.Producto.FindAsync(id);
            if (producto != null)
            {
                _context.Producto.Remove(producto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
          return (_context.Producto?.Any(e => e.Cod_producto == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to your death</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Productoes/Create.cshtml
@model pruevas_de_a_5.Models.Producto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom_producto" class="control-label"></label>
                <input asp-for="Nom_producto" class="form-control" />
                <span asp-validation-for="Nom_producto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha_Elaboracio" class="control-label"></label>
                <input asp-for="Fecha_Elaboracio" class="form-control" />
                <span asp-validation-for="Fecha_Elaboracio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha_Caducidad" class="control-label"></label>
                <input asp-for="Fecha_Caducidad" class="form-control" />
                <span asp-validation-for="Fecha_Caducidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodCategoria" class="control-label"></label>
                <input asp-for="CodCategoria" class="form-control" />
                <span asp-validation-for="CodCategoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodProveedor" class="control-label"></label>
                <input asp-for="CodProveedor" class="form-control" />
                <span asp-validation-for="CodProveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Productoes/Delete.cshtml
@model pruevas_de_a_5.Models.Producto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom_producto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom_producto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha_Elaboracio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha_Elaboracio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha_Caducidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha_Caducidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodCategoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodCategoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodProveedor)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Cod_producto" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Productoes/Details.cshtml
@model pruevas_de_a_5.Models.Producto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom_producto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom_producto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha_Elaboracio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha_Elaboracio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha_Caducidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha_Caducidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodCategoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodCategoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodProveedor)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Cod_producto">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Productoes/Edit.cshtml
@model pruevas_de_a_5.Models.Producto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Cod_producto" />
            <div class="form-group">
                <label asp-for="Nom_producto" class="control-label"></label>
                <input asp-for="Nom_producto" class="form-control" />
                <span asp-validation-for="Nom_producto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha_Elaboracio" class="control-label"></label>
                <input asp-for="Fecha_Elaboracio" class="form-control" />
                <span asp-validation-for="Fecha_Elaboracio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha_Caducidad" class="control-label"></label>
                <input asp-for="Fecha_Caducidad" class="form-control" />
                <span asp-validation-for="Fecha_Caducidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodCategoria" class="control-label"></label>
                <input asp-for="CodCategoria" class="form-control" />
                <span asp-validation-for="CodCategoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodProveedor" class="control-label"></label>
                <input asp-for="CodProveedor" class="form-control" />
                <span asp-validation-for="CodProveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Productoes/Index.cshtml
@model IEnumerable<pruevas_de_a_5.Models.Producto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom_producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha_Elaboracio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha_Caducidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodCategoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodProveedor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom_producto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_Elaboracio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_Caducidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodCategoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodProveedor)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Cod_producto">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Cod_producto">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Cod_producto">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - pruevas_de_a_5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/pruevas_de_a_5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">pruevas_de_a_5</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productoes" asp-action="Index">Productos</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - pruevas_de_a_5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>